---
title: "Reproducibility Report for 'A dual-pathway architecture for stress to disrupt agency and promote habit' by Giovanniello et al. (2025, Nature)"
author: "Tristan David"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

[No abstract is needed.]  Each reproducibility project will have a straightforward, no frills report of the study and reproducibility results. These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of your attempt to reproduce the results. Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for your reproducibility attempt, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  

The experiment I will simulate and reproduce comes from Giovaniello et al. (2025), which investigates how distinct nuclei of the amygdala and their projections to the striatum support supoprt goal-directed vs habitual behavior, and the disruption of these processes by chronic stress. Chronic, mild stress perturbs these brain regions, impairing a mouse’s ability to exert volitional control over actions, as measured by two gold-standard assessments of goal-directed behavior: outcome-devaluation and contingency degradation. 

The focus of my reproducibility report is to reproduce and simulate the authors' core argument that chronic stress disrupts goal-directed action and promotes habits, as indexed by insensitivity to contingency degradation. This behavioral finding is reflects a stress x contingency degradation group interaction on lever press rates.

The experiments described by this paper are important for my research program because it converges with my interest in circuit-specific mechanisms underlying disrupted behavioral control in models of alcohol dependence. Specifically, the finding of the existence and a functional role for CeA-DMS afferents really resonates with my research interests. The DMS is a nucleus within the basal ganglia that has a role in the acquisition of goal-directed behavior that supports adaptive decision-making. The CeA is a nucleus within the amygdalar complex that has become a focal point of research on incentive salience. These regions, when investigated on their own, are compromised in disease states such as ethanol dependence, and investigating amygdalar-striatal afferents will provide knowledge on neural mechanisms of disrupted motivational and cognitive control over decision-making.

In order to simulate this experiment, I will look over the available behavioral data from the paper and record the means and variabilities for individual aspects (mouse, session, rate). These metrics will be important for how I will want to simulate datasets. 

The main statistical analysis I will use to reproduce and simulate the main finding is a two-way ANOVA with stress and contingency degradation groups as factors. Lever-press rate during the contingency degradation probe test is what we will use as our measure. A challenge in simulation is capturing the variability of animal behavior, since performance will change across sessions and response acquisition will differ between animals.

Prior to running simulations, I will attempt to reproduce the analyses reported in the paper using the available data. The authors used a statistical analysis software called Prism on all quantitative data. I will use a different analysis software called JASP since it is free. I will only focus on reproducing the experiment that I intend to simulate– the effects of chronic stress on goal-directed action control.

https://github.com/tristantd/giovannielloetal2025.git

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Justification for choice of study

Please describe why you chose to reproduce the results of this study.

I am choosing to reproduce the results of this study because a crucial component for my research program is evaluating disruptions to behavioral control strategies in disease models--specifically, alcohol dependence. This study looks at the effects of chronic stress, while I want to investigate effects of chronic ethanol exposure. Additionally, this paper evaluates the contributions of distinct amygdalar-striatal circuitry in supporting goal-directed actions or enabling habit formation. I am interested in the role of amygdalar-circuitry in the context of incentive motivation. While this study looks at differnt roles of this pathway, it is only one of a few showing existence of CeA to dorsomedial straital afferents and a functional role. 

### Anticipated challenges

Do you anticipate running into any challenges when attempting to reproduce these result(s)? If so please, list them here.

I anticipate that capturing the natural variability of animal behavior will be difficult in simulation. I also think that because I will be using a different statistical analysis software, there will be differences in how the effects and statistics are reported. There are many experiments described in this paper. So one challenge is attempting to reproduce and then simulate all those experiments. Therefore, I will only focus on one: the effects of chronic stress on a contingency degredation probe test.

### Links

Project repository (on Github): https://github.com/tristantd/giovannielloetal2025.git

Original paper (as hosted in your repo): https://www.nature.com/articles/s41586-024-08580-w

## Methods

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study.

To evaluate the effects of chronic stress on goal-directed actions, I will simulate behavioral data for 29 mice (7 mice for the control, non-degraded group; 7 mice for the control, degraded group; 7 mice for the stress, non-degraded group; and 8 mice for the stress, degraded group). The primary confirmatory analysis will be a stress x contingency degradation group interaction, effect of contingency degradation, and no effect of stress.

The hypothesis I want to confirm is that chronic stress will reduce sensitivity to the action-outcome contingency (as evidenced by no reduction in lever press rate when contingency is degraded) which should produce a significant stress x contingency degradation group interaction where we would observe stress mice press equally in degraded and non-degraded conditions, whereas we would observe a reduced lever pressing in the degraded condition for control mice. This corresponds to figure 1i.

The parameter estimates we will use are means, SDs, SEMs, p-values. 

I will use a 2(control vs chronic stress) X 2(degraded vs nondegraded)

### Differences from original study

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results.

The differences from the original study are that this will be a simulation by which no behavioral data will be collected. Additionally, I will use a different statistical analysis software that the paper uses--they use Prism GraphPad and I will use JASP because it is free. I will use the same analysis, two-way ANOVA, for the simulated data. These differences will potentially influence my ability to reproduce the original results. For example, the differerent statistical analysis softwares may result in different reported values.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.

The outcome measure for the success of this reproducibility project will be if I can show the same effect that the authors claim in their paper. This will be comparing my simulated data with the authors' real reported data. This will be computed using an ANOVA on the simulated data and comparing effect sizes. 

### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).

I have now reproduced the statistics reported in the original paper. I have also made simulation code that simulates press rate based on the means and standard deviations of the groups. I need to figure out how to get the raw numbers from this data frame so that I can put it into an excel sheet and analyze/do statistical tests on JASP.


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
